linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - golint
    - gosec
    - interfacer
    - goconst
    - gocyclo
    - goimports
    - depguard
    - unparam
    - nakedret
    - prealloc
