#!/usr/bin/env python

import os
import json

os.chdir(os.path.dirname(os.path.realpath(__file__)))

for root, dirs, files in os.walk("in"):
    for fn in files:
        print("Converting %s" % fn)
        i = os.path.join(root, fn)
        o = os.path.join("out", fn)

        with open(i, 'r') as infile, open(o, 'w') as outfile:
            t = json.load(infile)

            # Flatten all the matches into the same space.
            t["matches"] = []
            for m in t["playoffs"]:
                t["matches"].append(m)
            t["matches"].append(t["semis"][0])
            t["matches"].append(t["semis"][1])
            t["matches"].append(t["final"])

            # Flatten the indexes and remove the kind
            for x, m in enumerate(t["matches"]):
                t["matches"][x]["index"] = x

            # Also convert the current to the new form
            t["current"] = len(t["matches"]) - 1

            # Remove the old match containers
            del t["playoffs"]
            del t["semis"]
            del t["final"]

            json.dump(t, outfile, indent=2)
